@baseUrl = http://localhost:3333
@authToken = {{athenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Dêssa Lessa",
    "email": "s.andressalessa@gmail.com",
    "password": "123456"
}

###

# @name athenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "s.andressa2@gmail.com",
    "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta 4",
    "content": "Conteudo da pergunta"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
POST {{baseUrl}}/questions/b4d08123-b5d5-4bf0-92ff-c00424831d6d/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "content": "Nova resposta",
    "authorId": "61d0029e-d02f-4e98-8a42-db07cf0f963a"
}
